// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exam struct {
	ID                  int64
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	OutsideSystemID     pgtype.Int4
	VisitID             pgtype.Int8
	MrnID               pgtype.Int8
	SiteID              pgtype.Int4
	ProcedureID         pgtype.Int4
	FinalReportID       pgtype.Int8
	AddendumReportID    pgtype.Int8
	Accession           string
	CurrentStatus       string
	ScheduleDt          pgtype.Timestamp
	BeginExamDt         pgtype.Timestamp
	EndExamDt           pgtype.Timestamp
	ExamCancelledDt     pgtype.Timestamp
	PrelimReportID      pgtype.Int8
	OrderingPhysicianID pgtype.Int8
	MessageID           pgtype.Int8
}

type Message struct {
	ID                   int64
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	FieldSeparator       string
	EncodingCharacters   string
	SendingApplication   string
	SendingFacility      string
	ReceivingApplication string
	ReceivingFacility    string
	ReceivedAt           pgtype.Timestamp
	MessageType          string
	TriggerEvent         string
	ControlID            string
	ProcessingID         string
	VersionID            string
}

type Metasite struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	IsOrg     bool
}

type Mrn struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	PatientID pgtype.Int8
	Mrn       string
	SiteID    int32
	MessageID pgtype.Int8
}

type OutsideSystem struct {
	ID         int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	MetasiteID pgtype.Int4
	Name       string
}

type Patient struct {
	ID         int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	FirstName  string
	LastName   string
	MiddleName pgtype.Text
	Suffix     pgtype.Text
	Prefix     pgtype.Text
	Degree     pgtype.Text
	Dob        pgtype.Date
	Sex        string
	Ssn        pgtype.Text
	HomePhone  pgtype.Text
	WorkPhone  pgtype.Text
	CellPhone  pgtype.Text
	MessageID  pgtype.Int8
}

type Physician struct {
	ID         int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	FirstName  string
	LastName   string
	MiddleName pgtype.Text
	Suffix     pgtype.Text
	Prefix     pgtype.Text
	Degree     pgtype.Text
	Npi        pgtype.Text
	Specialty  pgtype.Text
	AppCode    string
	MessageID  pgtype.Int8
}

type Procedure struct {
	ID          int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	SiteID      pgtype.Int4
	Code        string
	Description string
	Specialty   pgtype.Text
	Modality    pgtype.Text
	MessageID   pgtype.Int8
}

type Report struct {
	ID            int64
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	RadiologistID pgtype.Int8
	Body          string
	Impression    string
	ReportStatus  string
	SubmittedDt   pgtype.Timestamp
	MessageID     pgtype.Int8
}

type Site struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Code      string
	Name      pgtype.Text
	Address   string
	IsCms     bool
	MessageID pgtype.Int8
}

type Visit struct {
	ID              int64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	OutsideSystemID pgtype.Int4
	SiteID          pgtype.Int4
	MrnID           pgtype.Int8
	Number          string
	PatientType     int16
	MessageID       pgtype.Int8
}
