// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exam struct {
	ID               int64
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	OutsideSystemID  pgtype.Int4
	OrderID          pgtype.Int8
	VisitID          pgtype.Int8
	MrnID            pgtype.Int8
	SiteID           pgtype.Int4
	ProcedureID      pgtype.Int4
	FinalReportID    pgtype.Int8
	AddendumReportID pgtype.Int8
	Accession        string
	CurrentStatus    string
	ScheduleDt       pgtype.Timestamp
	BeginExamDt      pgtype.Timestamp
	EndExamDt        pgtype.Timestamp
}

type Message struct {
	ID                   int64
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	FieldSeparator       string
	EncodingCharacters   string
	SendingApplication   string
	SendingFacility      string
	ReceivingApplication string
	ReceivingFacility    string
	ReceivedAt           pgtype.Timestamp
	MessageType          string
	TriggerEvent         string
	ControlID            string
	ProcessingID         string
	VersionID            string
}

type Metasite struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	IsOrg     bool
}

type Mrn struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	PatientID pgtype.Int8
	Mrn       string
	SiteID    int32
}

type Order struct {
	ID                  int64
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	OutsideSystemID     pgtype.Int4
	SiteID              pgtype.Int4
	VisitID             pgtype.Int8
	MrnID               pgtype.Int8
	OrderingPhysicianID pgtype.Int8
	Arrival             pgtype.Timestamp
	Number              string
	CurrentStatus       string
}

type OutsideSystem struct {
	ID         int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	MetasiteID pgtype.Int4
	Name       string
}

type Patient struct {
	ID         int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	FirstName  string
	LastName   string
	MiddleName pgtype.Text
	Suffix     pgtype.Text
	Prefix     pgtype.Text
	Degree     pgtype.Text
	Dob        pgtype.Date
	Sex        string
	Ssn        pgtype.Text
	HomePhone  pgtype.Text
	WorkPhone  pgtype.Text
	CellPhone  pgtype.Text
}

type Physician struct {
	ID         int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	FirstName  string
	LastName   string
	MiddleName pgtype.Text
	Suffix     pgtype.Text
	Prefix     pgtype.Text
	Degree     pgtype.Text
	Npi        string
	Specialty  pgtype.Text
}

type Procedure struct {
	ID          int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	SiteID      pgtype.Int4
	Code        string
	Description string
	Specialty   pgtype.Text
	Modality    pgtype.Text
}

type Report struct {
	ID            int64
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	RadiologistID pgtype.Int8
	Body          string
	Impression    string
	ReportStatus  string
	SubmittedDt   pgtype.Timestamp
}

type Site struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Code      string
	Name      string
	Address   string
	IsCms     bool
}

type Visit struct {
	ID              int64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	OutsideSystemID pgtype.Int4
	SiteID          pgtype.Int4
	MrnID           pgtype.Int8
	Number          string
	PatientType     int16
}
