// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mrns.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMrn = `-- name: CreateMrn :one
INSERT INTO mrns (site_id, patient_id, mrn)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, patient_id, mrn, site_id
`

type CreateMrnParams struct {
	SiteID    int32
	PatientID pgtype.Int8
	Mrn       string
}

func (q *Queries) CreateMrn(ctx context.Context, arg CreateMrnParams) (Mrn, error) {
	row := q.db.QueryRow(ctx, createMrn, arg.SiteID, arg.PatientID, arg.Mrn)
	var i Mrn
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PatientID,
		&i.Mrn,
		&i.SiteID,
	)
	return i, err
}

const getMrnBySitePatient = `-- name: GetMrnBySitePatient :one
SELECT id, created_at, updated_at, patient_id, mrn, site_id
FROM mrns
WHERE
    site_id = $1
    AND patient_id = $2
`

type GetMrnBySitePatientParams struct {
	SiteID    int32
	PatientID pgtype.Int8
}

func (q *Queries) GetMrnBySitePatient(ctx context.Context, arg GetMrnBySitePatientParams) (Mrn, error) {
	row := q.db.QueryRow(ctx, getMrnBySitePatient, arg.SiteID, arg.PatientID)
	var i Mrn
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PatientID,
		&i.Mrn,
		&i.SiteID,
	)
	return i, err
}
