// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reports.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
WITH upsert as (
    INSERT INTO reports (
        radiologist_id,
        body,
        impression,
        report_status,
        submitted_dt
    )
    VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (radiologist_id, impression, report_status, submitted_dt) DO UPDATE
    SET
        body = COALESCE(EXCLUDED.body, reports.body)
    WHERE
        COALESCE(EXCLUDED.body, reports.body) IS DISTINCT FROM EXCLUDED.body
    RETURNING id, created_at, updated_at, radiologist_id, body, impression, report_status, submitted_dt
)

SELECT id, created_at, updated_at, radiologist_id, body, impression, report_status, submitted_dt FROM upsert
UNION ALL
SELECT id, created_at, updated_at, radiologist_id, body, impression, report_status, submitted_dt FROM reports
WHERE
    radiologist_id = $1
    AND impression = $3
    AND report_status = $4
    AND submitted_dt = $5
`

type CreateReportParams struct {
	RadiologistID pgtype.Int8
	Body          string
	Impression    string
	ReportStatus  string
	SubmittedDt   pgtype.Timestamp
}

type CreateReportRow struct {
	ID            int64
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	RadiologistID pgtype.Int8
	Body          string
	Impression    string
	ReportStatus  string
	SubmittedDt   pgtype.Timestamp
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.RadiologistID,
		arg.Body,
		arg.Impression,
		arg.ReportStatus,
		arg.SubmittedDt,
	)
	var i CreateReportRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RadiologistID,
		&i.Body,
		&i.Impression,
		&i.ReportStatus,
		&i.SubmittedDt,
	)
	return i, err
}

const getAllReports = `-- name: GetAllReports :many
SELECT id, created_at, updated_at, radiologist_id, body, impression, report_status, submitted_dt
FROM reports
`

func (q *Queries) GetAllReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.Query(ctx, getAllReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RadiologistID,
			&i.Body,
			&i.Impression,
			&i.ReportStatus,
			&i.SubmittedDt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportById = `-- name: GetReportById :one
SELECT id, created_at, updated_at, radiologist_id, body, impression, report_status, submitted_dt FROM reports
WHERE id = $1
`

func (q *Queries) GetReportById(ctx context.Context, id int64) (Report, error) {
	row := q.db.QueryRow(ctx, getReportById, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RadiologistID,
		&i.Body,
		&i.Impression,
		&i.ReportStatus,
		&i.SubmittedDt,
	)
	return i, err
}

const getReportByRadID = `-- name: GetReportByRadID :one
SELECT id, created_at, updated_at, radiologist_id, body, impression, report_status, submitted_dt FROM reports
where radiologist_id = $1
`

func (q *Queries) GetReportByRadID(ctx context.Context, radiologistID pgtype.Int8) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByRadID, radiologistID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RadiologistID,
		&i.Body,
		&i.Impression,
		&i.ReportStatus,
		&i.SubmittedDt,
	)
	return i, err
}

const getReportByUniqueFields = `-- name: GetReportByUniqueFields :one
SELECT id, created_at, updated_at, radiologist_id, body, impression, report_status, submitted_dt
FROM reports
WHERE
    radiologist_id = $1
    AND impression = $2
    AND report_status = $3
    AND submitted_dt = $4
`

type GetReportByUniqueFieldsParams struct {
	RadiologistID pgtype.Int8
	Impression    string
	ReportStatus  string
	SubmittedDt   pgtype.Timestamp
}

func (q *Queries) GetReportByUniqueFields(ctx context.Context, arg GetReportByUniqueFieldsParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByUniqueFields,
		arg.RadiologistID,
		arg.Impression,
		arg.ReportStatus,
		arg.SubmittedDt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RadiologistID,
		&i.Body,
		&i.Impression,
		&i.ReportStatus,
		&i.SubmittedDt,
	)
	return i, err
}
