// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reports.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    exam_id,
    radiologist_id,
    body,
    impression,
    report_status,
    submitted_dt
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, exam_id, radiologist_id, body, impression, report_status, submitted_dt
`

type CreateReportParams struct {
	ExamID        pgtype.Int8
	RadiologistID pgtype.Int8
	Body          string
	Impression    string
	ReportStatus  string
	SubmittedDt   pgtype.Timestamp
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ExamID,
		arg.RadiologistID,
		arg.Body,
		arg.Impression,
		arg.ReportStatus,
		arg.SubmittedDt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExamID,
		&i.RadiologistID,
		&i.Body,
		&i.Impression,
		&i.ReportStatus,
		&i.SubmittedDt,
	)
	return i, err
}
