version: 2
project_name: volta

before:
  hooks:
    - go mod tidy
builds:
  - binary: volta
    main: ./cmd/service
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version=v{{ .Version }}"
