steps:
  - name: golang:1.23
    id: "run-goose"
    entrypoint: bash
    args:
      - "-c"
      - |
        go install github.com/pressly/goose/v3/cmd/goose@latest
        goose postgres "host=$$DB_HOST port=5432 user=$$DB_USER dbname=$$DB_NAME sslmode=disable" up
    dir: sql/schema
    env:
      - "PGPASSWORD=$$DB_PASSWORD"
      - "DB_USER=$$DB_USER"
      - "DB_PASSWORD=$$DB_PASSWORD"
      - "DB_NAME=$$DB_NAME"
      - "DB_HOST=$$DB_HOST"

availableSecrets:
  secretManager:
    - versionName: projects/$_GCP_PROJECT_ID/secrets/DB_USER/versions/latest
      env: DB_USER
    - versionName: projects/$_GCP_PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: DB_PASSWORD
    - versionName: projects/$_GCP_PROJECT_ID/secrets/DB_NAME/versions/latest
      env: DB_NAME
    - versionName: projects/$_GCP_PROJECT_ID/secrets/DB_HOST/versions/latest
      env: DB_HOST

substitutions:
  _GCP_PROJECT_ID: ""
