steps:
  - name: golang:1.23
    id: "run-goose"
    entrypoint: bash
    args:
      - "-c"
      - |
        go install github.com/pressly/goose/v3/cmd/goose@latest
        goose postgres "host=10.70.80.3 port=5432 user=postgres password=postgres dbname=postgres sslmode=disable" up
    dir: sql/schema
    env:
      - "PGPASSWORD=postgres"

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: projects/silver-pact-448614-t7/locations/us-central1/workerPools/cd-build-pool
