-- +goose Up
ALTER TABLE IF EXISTS sites DROP CONSTRAINT IF EXISTS sites_code_name_unique;
ALTER TABLE IF EXISTS sites ALTER COLUMN name DROP NOT NULL;
ALTER TABLE IF EXISTS sites ADD CONSTRAINT sites_code_unique UNIQUE (code);

ALTER TABLE IF EXISTS physicians ALTER COLUMN npi DROP NOT NULL;
UPDATE physicians SET app_code = 'MISSING' WHERE app_code IS NULL;
ALTER TABLE IF EXISTS physicians ALTER COLUMN app_code SET NOT NULL;

-- +goose Down
ALTER TABLE IF EXISTS physicians ALTER COLUMN app_code DROP NOT NULL;
ALTER TABLE IF EXISTS physicians ALTER COLUMN npi SET NOT NULL;

ALTER TABLE IF EXISTS sites DROP CONSTRAINT IF EXISTS sites_code_unique;
ALTER TABLE IF EXISTS sites ALTER COLUMN name SET NOT NULL;
ALTER TABLE IF EXISTS sites ADD CONSTRAINT sites_code_name_unique UNIQUE (code, name);
