-- +goose Up
ALTER TABLE IF EXISTS patients ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS mrns ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS sites ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS visits ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS physicians ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS procedures ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS reports ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS exams ADD COLUMN message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE;

-- +goose Down
ALTER TABLE IF EXISTS patients DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS mrns DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS sites DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS visits DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS physicians DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS procedures DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS reports DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS exams DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS patients DROP COLUMN IF EXISTS message_id;
ALTER TABLE IF EXISTS patients DROP COLUMN IF EXISTS message_id;
