name: Deploy Volta to GCP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          export_default_credentials: true          

      - name: Setup Proxy Database
        run: |
          docker run -d \
            -v ${{ secrets.GCP_SA_KEY }}:/config \
            -p 127.0.0.1:3306:3306 \
            gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.2 \
            --credential_file /config ${{ secrets.INSTANCE_CONNECTION_NAME}}
      
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Apply Migrations
        run: |
          goose -dir sql/schema postgres postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@tcp(127.0.0.1:3306/${{ secrets.DB_NAME}}) up
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME}}

