name: Migrate Database with Goose

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: GCP Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
    
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit Cloud Build
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml . \
            --worker-pool=${{ secrets.GCP_WORKER_POOL }} \
            --substitutions=_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},\
                _PROJECT_LOCATION=${{ secrets.GCP_PROJECT_LOCATION }},\
