name: volta-ci

on:
    push:
        branches:
        - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Unit Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.24.0'
            - name: Install tparse
              run: go install github.com/mfridman/tparse@main
            - name: Run tests
              run: |
                mkdir -p bin
                go vet ./...
                go build ./...
                make test-packages
            - name: Install gosec
              run: go install github.com/securego/gosec/v2/cmd/gosec@latest
            - name: Security check
              run: gosec -terse ./...
